// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PsuHistory.Data.EF.SQL.Context;

namespace PsuHistory.Data.EF.SQL.Migrations.PostgresMigrations
{
    [DbContext(typeof(DbContextPostgres))]
    [Migration("20210607191102_AddNewField")]
    partial class AddNewField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Histories.AttachmentForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("AttachmentForms");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Histories.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.AttachmentBurial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BurialId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BurialId");

                    b.ToTable("AttachmentBurials");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.BirthPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BirthPlaces");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.Burial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<int>("KnownNumber")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("NumberBurial")
                        .HasColumnType("integer");

                    b.Property<Guid>("TypeBurialId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnknownNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeBurialId");

                    b.ToTable("Burials");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.ConscriptionPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ConscriptionPlaces");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.DutyStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("DutyStations");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.TypeBurial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("TypeBurials");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.TypeVictim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("TypeVictims");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.Victim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BirthPlaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BurialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConscriptionPlaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DateOfBirth")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DateOfDeath")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("DutyStationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsHeroSoviet")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPartisan")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TypeVictimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BirthPlaceId");

                    b.HasIndex("BurialId");

                    b.HasIndex("ConscriptionPlaceId");

                    b.HasIndex("DutyStationId");

                    b.HasIndex("TypeVictimId");

                    b.ToTable("Victims");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1228a08d-9596-4b86-9125-f42833590414"),
                            CreatedAt = new DateTime(2021, 6, 7, 19, 11, 1, 560, DateTimeKind.Utc).AddTicks(8673),
                            Name = "Owner",
                            UpdatedAt = new DateTime(2021, 6, 7, 19, 11, 1, 560, DateTimeKind.Utc).AddTicks(8673)
                        },
                        new
                        {
                            Id = new Guid("ddb44385-fa68-489e-bd46-f30f6ffe5786"),
                            CreatedAt = new DateTime(2021, 6, 7, 19, 11, 1, 560, DateTimeKind.Utc).AddTicks(8673),
                            Name = "Admin",
                            UpdatedAt = new DateTime(2021, 6, 7, 19, 11, 1, 560, DateTimeKind.Utc).AddTicks(8673)
                        },
                        new
                        {
                            Id = new Guid("68611f87-f6bb-4490-b2c3-a7ab3b502823"),
                            CreatedAt = new DateTime(2021, 6, 7, 19, 11, 1, 560, DateTimeKind.Utc).AddTicks(8673),
                            Name = "Moderator",
                            UpdatedAt = new DateTime(2021, 6, 7, 19, 11, 1, 560, DateTimeKind.Utc).AddTicks(8673)
                        });
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2017b538-ac76-4633-baf8-80f0bec88856"),
                            CreatedAt = new DateTime(2021, 6, 7, 19, 11, 1, 560, DateTimeKind.Utc).AddTicks(8673),
                            Mail = "Owner",
                            Password = "AQAAAAEAACcQAAAAENAnCVyWq0lo9yySX3Ka7WMkN6jmIjUBKz1CohwrKt5ngJpr5Pq4fY4sLSXWs3ul/A==",
                            RoleId = new Guid("1228a08d-9596-4b86-9125-f42833590414"),
                            UpdatedAt = new DateTime(2021, 6, 7, 19, 11, 1, 560, DateTimeKind.Utc).AddTicks(8673)
                        },
                        new
                        {
                            Id = new Guid("2e93ac0c-3053-4fc1-ad54-7b1dff9b1f5b"),
                            CreatedAt = new DateTime(2021, 6, 7, 19, 11, 1, 560, DateTimeKind.Utc).AddTicks(8673),
                            Mail = "Admin",
                            Password = "AQAAAAEAACcQAAAAENAnCVyWq0lo9yySX3Ka7WMkN6jmIjUBKz1CohwrKt5ngJpr5Pq4fY4sLSXWs3ul/A==",
                            RoleId = new Guid("ddb44385-fa68-489e-bd46-f30f6ffe5786"),
                            UpdatedAt = new DateTime(2021, 6, 7, 19, 11, 1, 560, DateTimeKind.Utc).AddTicks(8673)
                        },
                        new
                        {
                            Id = new Guid("d42aef05-d907-4cb2-9401-5800513f8a54"),
                            CreatedAt = new DateTime(2021, 6, 7, 19, 11, 1, 560, DateTimeKind.Utc).AddTicks(8673),
                            Mail = "Moderator",
                            Password = "AQAAAAEAACcQAAAAENAnCVyWq0lo9yySX3Ka7WMkN6jmIjUBKz1CohwrKt5ngJpr5Pq4fY4sLSXWs3ul/A==",
                            RoleId = new Guid("68611f87-f6bb-4490-b2c3-a7ab3b502823"),
                            UpdatedAt = new DateTime(2021, 6, 7, 19, 11, 1, 560, DateTimeKind.Utc).AddTicks(8673)
                        });
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Histories.AttachmentForm", b =>
                {
                    b.HasOne("PsuHistory.Data.Domain.Models.Histories.Form", "Form")
                        .WithMany("AttachmentForms")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.AttachmentBurial", b =>
                {
                    b.HasOne("PsuHistory.Data.Domain.Models.Monuments.Burial", "Burial")
                        .WithMany("AttachmentBurials")
                        .HasForeignKey("BurialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Burial");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.Burial", b =>
                {
                    b.HasOne("PsuHistory.Data.Domain.Models.Monuments.TypeBurial", "TypeBurial")
                        .WithMany()
                        .HasForeignKey("TypeBurialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeBurial");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.Victim", b =>
                {
                    b.HasOne("PsuHistory.Data.Domain.Models.Monuments.BirthPlace", "BirthPlace")
                        .WithMany()
                        .HasForeignKey("BirthPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PsuHistory.Data.Domain.Models.Monuments.Burial", "Burial")
                        .WithMany()
                        .HasForeignKey("BurialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PsuHistory.Data.Domain.Models.Monuments.ConscriptionPlace", "ConscriptionPlace")
                        .WithMany()
                        .HasForeignKey("ConscriptionPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PsuHistory.Data.Domain.Models.Monuments.DutyStation", "DutyStation")
                        .WithMany()
                        .HasForeignKey("DutyStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PsuHistory.Data.Domain.Models.Monuments.TypeVictim", "TypeVictim")
                        .WithMany()
                        .HasForeignKey("TypeVictimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirthPlace");

                    b.Navigation("Burial");

                    b.Navigation("ConscriptionPlace");

                    b.Navigation("DutyStation");

                    b.Navigation("TypeVictim");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Users.User", b =>
                {
                    b.HasOne("PsuHistory.Data.Domain.Models.Users.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Histories.Form", b =>
                {
                    b.Navigation("AttachmentForms");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.Burial", b =>
                {
                    b.Navigation("AttachmentBurials");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Users.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
