// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PsuHistory.Data.EF.SQL.Context;

namespace PsuHistory.Data.EF.SQL.Migrations.MySqlMigrations
{
    [DbContext(typeof(DbContextMySql))]
    [Migration("20210607191511_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Histories.AttachmentForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<Guid>("FormId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("AttachmentForms");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Histories.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.AttachmentBurial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BurialId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BurialId");

                    b.ToTable("AttachmentBurials");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.BirthPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("BirthPlaces");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.Burial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<int>("KnownNumber")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("NumberBurial")
                        .HasColumnType("int");

                    b.Property<Guid>("TypeBurialId")
                        .HasColumnType("char(36)");

                    b.Property<int>("UnknownNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeBurialId");

                    b.ToTable("Burials");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.ConscriptionPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ConscriptionPlaces");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.DutyStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("DutyStations");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.TypeBurial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("TypeBurials");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.TypeVictim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("TypeVictims");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.Victim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BirthPlaceId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BurialId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConscriptionPlaceId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateOfBirth")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("DateOfDeath")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("DutyStationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsHeroSoviet")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPartisan")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("TypeVictimId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BirthPlaceId");

                    b.HasIndex("BurialId");

                    b.HasIndex("ConscriptionPlaceId");

                    b.HasIndex("DutyStationId");

                    b.HasIndex("TypeVictimId");

                    b.ToTable("Victims");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8722d261-9a84-4f52-86c8-b2b6f5818b38"),
                            CreatedAt = new DateTime(2021, 6, 7, 19, 15, 11, 482, DateTimeKind.Utc).AddTicks(1894),
                            Name = "Owner",
                            UpdatedAt = new DateTime(2021, 6, 7, 19, 15, 11, 482, DateTimeKind.Utc).AddTicks(1894)
                        },
                        new
                        {
                            Id = new Guid("bfa7197a-5b8a-4873-a741-a1cf7ecd8822"),
                            CreatedAt = new DateTime(2021, 6, 7, 19, 15, 11, 482, DateTimeKind.Utc).AddTicks(1894),
                            Name = "Admin",
                            UpdatedAt = new DateTime(2021, 6, 7, 19, 15, 11, 482, DateTimeKind.Utc).AddTicks(1894)
                        },
                        new
                        {
                            Id = new Guid("906f9954-fc61-4b0f-b7ec-55ce7570bbde"),
                            CreatedAt = new DateTime(2021, 6, 7, 19, 15, 11, 482, DateTimeKind.Utc).AddTicks(1894),
                            Name = "Moderator",
                            UpdatedAt = new DateTime(2021, 6, 7, 19, 15, 11, 482, DateTimeKind.Utc).AddTicks(1894)
                        });
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("89967998-d84a-463f-872d-2464ca5cefc2"),
                            CreatedAt = new DateTime(2021, 6, 7, 19, 15, 11, 482, DateTimeKind.Utc).AddTicks(1894),
                            Mail = "Owner",
                            Password = "AQAAAAEAACcQAAAAENAnCVyWq0lo9yySX3Ka7WMkN6jmIjUBKz1CohwrKt5ngJpr5Pq4fY4sLSXWs3ul/A==",
                            RoleId = new Guid("8722d261-9a84-4f52-86c8-b2b6f5818b38"),
                            UpdatedAt = new DateTime(2021, 6, 7, 19, 15, 11, 482, DateTimeKind.Utc).AddTicks(1894)
                        },
                        new
                        {
                            Id = new Guid("84ffafbd-1481-468a-85ac-e50dd1321f0b"),
                            CreatedAt = new DateTime(2021, 6, 7, 19, 15, 11, 482, DateTimeKind.Utc).AddTicks(1894),
                            Mail = "Admin",
                            Password = "AQAAAAEAACcQAAAAENAnCVyWq0lo9yySX3Ka7WMkN6jmIjUBKz1CohwrKt5ngJpr5Pq4fY4sLSXWs3ul/A==",
                            RoleId = new Guid("bfa7197a-5b8a-4873-a741-a1cf7ecd8822"),
                            UpdatedAt = new DateTime(2021, 6, 7, 19, 15, 11, 482, DateTimeKind.Utc).AddTicks(1894)
                        },
                        new
                        {
                            Id = new Guid("fb36c000-9ce3-4482-a194-64987ae71435"),
                            CreatedAt = new DateTime(2021, 6, 7, 19, 15, 11, 482, DateTimeKind.Utc).AddTicks(1894),
                            Mail = "Moderator",
                            Password = "AQAAAAEAACcQAAAAENAnCVyWq0lo9yySX3Ka7WMkN6jmIjUBKz1CohwrKt5ngJpr5Pq4fY4sLSXWs3ul/A==",
                            RoleId = new Guid("906f9954-fc61-4b0f-b7ec-55ce7570bbde"),
                            UpdatedAt = new DateTime(2021, 6, 7, 19, 15, 11, 482, DateTimeKind.Utc).AddTicks(1894)
                        });
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Histories.AttachmentForm", b =>
                {
                    b.HasOne("PsuHistory.Data.Domain.Models.Histories.Form", "Form")
                        .WithMany("AttachmentForms")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.AttachmentBurial", b =>
                {
                    b.HasOne("PsuHistory.Data.Domain.Models.Monuments.Burial", "Burial")
                        .WithMany("AttachmentBurials")
                        .HasForeignKey("BurialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Burial");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.Burial", b =>
                {
                    b.HasOne("PsuHistory.Data.Domain.Models.Monuments.TypeBurial", "TypeBurial")
                        .WithMany()
                        .HasForeignKey("TypeBurialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeBurial");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.Victim", b =>
                {
                    b.HasOne("PsuHistory.Data.Domain.Models.Monuments.BirthPlace", "BirthPlace")
                        .WithMany()
                        .HasForeignKey("BirthPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PsuHistory.Data.Domain.Models.Monuments.Burial", "Burial")
                        .WithMany()
                        .HasForeignKey("BurialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PsuHistory.Data.Domain.Models.Monuments.ConscriptionPlace", "ConscriptionPlace")
                        .WithMany()
                        .HasForeignKey("ConscriptionPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PsuHistory.Data.Domain.Models.Monuments.DutyStation", "DutyStation")
                        .WithMany()
                        .HasForeignKey("DutyStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PsuHistory.Data.Domain.Models.Monuments.TypeVictim", "TypeVictim")
                        .WithMany()
                        .HasForeignKey("TypeVictimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirthPlace");

                    b.Navigation("Burial");

                    b.Navigation("ConscriptionPlace");

                    b.Navigation("DutyStation");

                    b.Navigation("TypeVictim");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Users.User", b =>
                {
                    b.HasOne("PsuHistory.Data.Domain.Models.Users.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Histories.Form", b =>
                {
                    b.Navigation("AttachmentForms");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Monuments.Burial", b =>
                {
                    b.Navigation("AttachmentBurials");
                });

            modelBuilder.Entity("PsuHistory.Data.Domain.Models.Users.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
